version: '3'

services:
  app:
    build: .
    container_name: cultivar-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - SECRET_KEY=change_this_to_a_secure_key
      - CULTIVAR_DB_DRIVER=postgres
      - CULTIVAR_DB_HOST=db
      - CULTIVAR_DB_PORT=5432
      - CULTIVAR_DB_USER=cultivar
      - CULTIVAR_DB_PASSWORD=cultivar
      - CULTIVAR_DB_NAME=cultivardb
      - CULTIVAR_PORT=5000
      - DEBUG=false
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: cultivar-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cultivar
      - POSTGRES_PASSWORD=cultivar
      - POSTGRES_DB=cultivardb

volumes:
  postgres_data:
