"""add_seedfinder_fields_to_breeder_and_cultivar

Revision ID: 109317dd2a2f
Revises: 3968dfa9e747
Create Date: 2025-11-06 12:43:40.776381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision: str = '109317dd2a2f'
down_revision: Union[str, Sequence[str], None] = '3968dfa9e747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to add SeedFinder fields and indexes."""
    bind = op.get_bind()
    dialect_name = bind.dialect.name

    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seedfinder_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_index('ix_breeder_seedfinder_id', ['seedfinder_id'], unique=True)

    with op.batch_alter_table('cultivar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('parent_2', sa.String(length=100), nullable=True))
        if dialect_name == 'postgresql':
            batch_op.add_column(sa.Column('lineage_json', JSONB, nullable=True))
        else:
            batch_op.add_column(sa.Column('lineage_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('seedfinder_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('thc_content', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cbd_content', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('flowering_type', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_cultivar_parent_1', ['parent_1'], unique=False)
        batch_op.create_index('ix_cultivar_parent_2', ['parent_2'], unique=False)
        batch_op.create_index('ix_cultivar_seedfinder_id', ['seedfinder_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema to remove SeedFinder fields and indexes."""
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('cultivar', schema=None) as batch_op:
        batch_op.drop_index('ix_cultivar_seedfinder_id')
        batch_op.drop_index('ix_cultivar_parent_2')
        batch_op.drop_index('ix_cultivar_parent_1')
        batch_op.drop_column('flowering_type')
        batch_op.drop_column('cbd_content')
        batch_op.drop_column('thc_content')
        batch_op.drop_column('seedfinder_id')
        batch_op.drop_column('lineage_json')
        batch_op.drop_column('parent_2')
        batch_op.drop_column('parent_1')

    with op.batch_alter_table('breeder', schema=None) as batch_op:
        batch_op.drop_index('ix_breeder_seedfinder_id')
        batch_op.drop_column('description')
        batch_op.drop_column('seedfinder_id')
        batch_op.drop_column('website')
        batch_op.drop_column('country')
    # ### end Alembic commands ###