"""Generate baseline schema for async models

Revision ID: 3968dfa9e747
Revises: 
Create Date: 2025-10-30 18:55:35.925551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3968dfa9e747'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('date_key', sa.DateTime(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_summary', schema=None) as batch_op:
        batch_op.create_index('ix_activity_summary_activity_type', ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_summary_date_key'), ['date_key'], unique=False)
        batch_op.create_index('ix_activity_summary_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_summary_summary_type'), ['summary_type'], unique=False)
        batch_op.create_index('ix_activity_summary_type_date', ['summary_type', 'date_key'], unique=False)

    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=160), nullable=True),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=True)

    op.create_table('breeder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_installed', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extension_slug'), ['slug'], unique=True)

    op.create_table('lead_magnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subscription_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('subscription_date', sa.DateTime(), nullable=False),
    sa.Column('unsubscribe_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscriber_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_newsletter_subscriber_phone'), ['phone'], unique=True)

    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('cultivar_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('grow_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=False),
    sa.Column('current_height', sa.String(length=20), nullable=True),
    sa.Column('start_dt', sa.DateTime(), nullable=False),
    sa.Column('height_date', sa.DateTime(), nullable=True),
    sa.Column('last_water_date', sa.DateTime(), nullable=True),
    sa.Column('last_feed_date', sa.DateTime(), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('est_harvest_date', sa.DateTime(), nullable=True),
    sa.Column('germination_date', sa.DateTime(), nullable=True),
    sa.Column('seedling_date', sa.DateTime(), nullable=True),
    sa.Column('vegetative_date', sa.DateTime(), nullable=True),
    sa.Column('flowering_date', sa.DateTime(), nullable=True),
    sa.Column('curing_date', sa.DateTime(), nullable=True),
    sa.Column('harvest_weight', sa.Float(), nullable=True),
    sa.Column('cycle_time', sa.Integer(), nullable=True),
    sa.Column('is_clone', sa.Boolean(), nullable=False),
    sa.Column('autoflower', sa.Boolean(), nullable=False),
    sa.Column('cultivar_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cultivar_id'], ['cultivar.id'], ),
    sa.ForeignKeyConstraint(['grow_id'], ['grow.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('featured_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_slug'), ['slug'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('is_verified_breeder', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('experience', sa.String(length=20), nullable=True),
    sa.Column('priority_tier', sa.String(length=20), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['waitlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_email'), ['email'], unique=True)

    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('is_system_activity', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index('ix_activity_activity_type', ['activity_type'], unique=False)
        batch_op.create_index('ix_activity_entity_type_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_activity_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_activity_timestamp', ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_type'), ['type'], unique=False)
        batch_op.create_index('ix_activity_user_id', ['user_id'], unique=False)

    op.create_table('cultivar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('breeder_id', sa.Integer(), nullable=True),
    sa.Column('indica', sa.Integer(), nullable=False),
    sa.Column('sativa', sa.Integer(), nullable=False),
    sa.Column('autoflower', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('seed_count', sa.Integer(), nullable=False),
    sa.Column('cycle_time', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['breeder_id'], ['breeder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_magnet_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_magnet_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('download_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_magnet_id'], ['lead_magnet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)

    op.create_table('plant_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_activity_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index('ix_plant_activity_date', ['date'], unique=False)
        batch_op.create_index('ix_plant_activity_plant_id', ['plant_id'], unique=False)
        batch_op.create_index('ix_plant_activity_user_id', ['user_id'], unique=False)

    op.create_table('plant_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('image_description', sa.Text(), nullable=True),
    sa.Column('image_order', sa.Integer(), nullable=True),
    sa.Column('image_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('show', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('ac_infinity_device_id', sa.Integer(), nullable=True),
    sa.Column('ecowitt_device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_data_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_data_sensor_id'), ['sensor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_data_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_data_created_at'))

    op.drop_table('sensor_data')
    op.drop_table('order_item')
    op.drop_table('sensor')
    op.drop_table('plant_image')
    with op.batch_alter_table('plant_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_plant_activity_user_id')
        batch_op.drop_index('ix_plant_activity_plant_id')
        batch_op.drop_index('ix_plant_activity_date')
        batch_op.drop_index(batch_op.f('ix_plant_activity_activity_type'))

    op.drop_table('plant_activity')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_number'))

    op.drop_table('order')
    op.drop_table('measurement')
    op.drop_table('lead_magnet_download')
    op.drop_table('grow')
    op.drop_table('cultivar')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_user_id')
        batch_op.drop_index(batch_op.f('ix_activity_type'))
        batch_op.drop_index('ix_activity_timestamp')
        batch_op.drop_index('ix_activity_is_active')
        batch_op.drop_index('ix_activity_entity_type_id')
        batch_op.drop_index('ix_activity_activity_type')

    op.drop_table('activity')
    op.drop_table('zone')
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_email'))

    op.drop_table('waitlist')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('stream')
    op.drop_table('status')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_slug'))

    op.drop_table('product')
    op.drop_table('plant')
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriber_phone'))
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriber_email'))

    op.drop_table('newsletter_subscriber')
    op.drop_table('metric')
    op.drop_table('lead_magnet')
    with op.batch_alter_table('extension', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extension_slug'))

    op.drop_table('extension')
    op.drop_table('breeder')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))

    op.drop_table('blog_post')
    with op.batch_alter_table('activity_summary', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_summary_type_date')
        batch_op.drop_index(batch_op.f('ix_activity_summary_summary_type'))
        batch_op.drop_index('ix_activity_summary_entity')
        batch_op.drop_index(batch_op.f('ix_activity_summary_date_key'))
        batch_op.drop_index('ix_activity_summary_activity_type')

    op.drop_table('activity_summary')
    # ### end Alembic commands ###
