"""Add strain_id aliases for backward compatibility

Revision ID: 6e5b1d353dd6
Revises: 109317dd2a2f
Create Date: 2025-11-06 21:58:09.106567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e5b1d353dd6'
down_revision: Union[str, Sequence[str], None] = '109317dd2a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeder', schema=None) as batch_op:
        batch_op.create_unique_constraint('ux_breeder_seedfinder_id', ['seedfinder_id'])

    with op.batch_alter_table('cultivar', schema=None) as batch_op:
        batch_op.alter_column('lineage_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.create_unique_constraint('ux_cultivar_seedfinder_id', ['seedfinder_id'])

    # Add strain_id alias columns for backward compatibility
    # Add nullable strain_id column to plant table
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strain_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plant_strain_id', 'cultivar', ['strain_id'], ['id'])

    # Add nullable strain_url column to plant table
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strain_url', sa.String(length=255), nullable=True))

    # Backfill strain_id with current cultivar_id values
    op.execute("UPDATE plant SET strain_id = cultivar_id WHERE strain_id IS NULL")

    # Add nullable strain_name property support (for legacy access patterns)
    # Note: strain_name is typically a computed property, so no database column needed

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plant_strain_id', type_='foreignkey')
        batch_op.drop_column('strain_id')
        batch_op.drop_column('strain_url')

    with op.batch_alter_table('cultivar', schema=None) as batch_op:
        batch_op.drop_constraint('ux_cultivar_seedfinder_id', type_='unique')
        batch_op.alter_column('lineage_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('breeder', schema=None) as batch_op:
        batch_op.drop_constraint('ux_breeder_seedfinder_id', type_='unique')

    op.drop_table('system_activity')
    # ### end Alembic commands ###
